[build]
  # This will be run the site build
  command = "npm run generate && npm run build:functions"
  # This is the directory is publishing to netlify's CDN
  publish = "dist"
  # functions build directory
  functions = "functions-build"
  framework = "#custom"
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' *.gny.io;"
    